
### Learn how to use R Studio to make a visualization of COVID-19 that will help encourage everyone to do their part to end the coronavirus!

```{r setup}

# Use the command echo = TRUE to show the code! This is programmed in R Studio using R Markdown, 
# but I used this command to display the code on this HTML page using echo = TRUE.

knitr::opts_chunk$set(echo = TRUE)

# I need to use several packages and libraries available for download through RStudio 
# in order to make this data visualization.

library(tidyverse)
library(plotly)

# This data on COVID-19 comes from the data repository for the 2019 Novel
# Coronavirus Visual Dashboard operated by the Johns Hopkins University
# Center for Systems Science and Engineering (JHU CSSE). Learn more about the data here:
# https://github.com/CSSEGISandData/COVID-19. Load the most up-to-date data
# by changing the date at the end of the file name.

covid <- read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/04-29-2020.csv")
```

```{r}

# I wanted to select the region, latitude, longitude, confirmed cases, and
# number of death variables from the data. I also made a new variable called
# "region" that combines the city, province/state, and country name if
# applicable.

data <- covid %>% 
  select(Admin2, Province_State, Country_Region, Lat, Long_, Confirmed, Deaths) %>%
  mutate(region = case_when(
    is.na(Admin2) & is.na(Province_State) ~ Country_Region,
    is.na(Admin2) & !is.na(Province_State) ~ paste(Province_State, Country_Region, sep = ", "),
    !is.na(Admin2) & !is.na(Province_State) ~ paste(Admin2, Province_State, Country_Region, sep = ", ")
  ))

data
```

```{r, warning = FALSE}

# Go to https://account.mapbox.com/access-tokens/ to get an API access token to
# configure Mapbox GL JS, Mobile, and Mapbox web services like routing and
# geocoding.

Sys.setenv("MAPBOX_TOKEN" = 
          "pk.eyJ1IjoiamVkd2FyZHMyMSIsImEiOiJjazhyamRoaDIwNmo5M2RtenNoNTBlOW9mIn0.RCk9CZZqefyJMNnH76LhaQ")

# Use the plot_mapbox command to initiate a plotly_mapbox object. The size of
# circles on the map correspond to the number of confirmed cases in a region
# with size = ~Confirmed, and the tooltips on the map show the location name and
# number of confirmed cases.

data %>% 
  plot_mapbox(lat = ~Lat, lon = ~Long_,
              hoverinfo = "text",
              size = ~Confirmed,
              text = ~paste(region, "\nConfirmed Cases:", Confirmed),
              mode = "scattermapbox") %>% 
  
  # Use layout to change the design of the map. I changed the title, font,
  # background color, and margins.
  
  layout(title = "Worldwide COVID-19 Confirmed Cases: April 29, 2020",
         font = list(color = "white"),
         plot_bgcolor = "#191A1A", paper_bgcolor = "#191A1A",
         mapbox = list(style = "dark"),
         margin = list(l = 10, r = 10,
                       b = 10, t = 50,
                       pad = 2)) %>% 
  
  # Use the config command to set the Mapbox API access token to the long string
  # of characters defined above.
  
  config(mapboxAccessToken = Sys.getenv("MAPBOX_TOKEN"))
```
